package:
  name: xinterpdf
  version: 0.1.0

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python 2.7*
    - setuptools
    - diffpy-cmi
    - matplotlib ==2.0.2
  run:
    - python 2.7*
    - setuptools
    - diffpy-cmi
    - matplotlib ==2.0.2

about:
  home: https://github.com/curieshicy/xINTERPDF
  summary: a GUI tool for analyzing X-ray PDF data for organics
  license: MIT
